backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: assets

collections:
  - name: blogs
    label: Blogs
    folder: content/blogs
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }
  - name: projects
    label: Projects
    folder: content/projects
    create: true
    fields:
      - { name: title, label: Title }
      - { name: startdate, label: Start Date, widget: date }
      - { name: enddate, label: End Date, widget: date }
      - { name: body, label: Body, widget: markdown }
  - name: organizations
    label: Organizations
    folder: content/organizations
    create: true
    fields:
      - { name: title, label: Title }
      - { name: startdate, label: Start Date, widget: date }
      - { name: enddate, label: End Date, widget: date }
      - { name: body, label: Body, widget: markdown }
